export const CATCH_POKEMON = {
  REQUEST: 'CATCH_POKEMON_REQUEST',
  SUCCESS: 'CATCH_POKEMON_SUCCESS',
  FAILURE: 'CATCH_POKEMON_FAILURE',
};

export const FETCH_POKEMON = {
  REQUEST: 'FETCH_POKEMON_REQUEST',
  SUCCESS: 'FETCH_POKEMON_SUCCESS',
  FAILURE: 'FETCH_POKEMON_FAILURE',
};

export const FETCH_POKEMONS = {
  REQUEST: 'FETCH_POKEMONS_REQUEST',
  SUCCESS: 'FETCH_POKEMONS_SUCCESS',
  FAILURE: 'FETCH_POKEMONS_FAILURE',
};

export const SWITCH_PAGE_POKEMONS = 'SWITCH_PAGE';
export const SWITCH_PAGE_CATCHED = 'SWITCH_PAGE_CATCHED';