export const GET_POKEMONS_LOADING = "GET_POKEMONS_LOADING";
export const GET_POKEMONS_SUCCESS = "GET_POKEMONS_SUCCESS";
export const GET_POKEMONS_FAIL = "GET_POKEMONS_FAIL";

export const ARE_ALL_POKEMONS_LOADED = "ARE_ALL_POKEMONS_LOADED";

export const GET_CAUGHT_POKEMONS_LOADING = "GET_CAUGHT_POKEMONS_LOADING";
export const GET_CAUGHT_POKEMONS_SUCCESS = "GET_CAUGHT_POKEMONS";
export const GET_CAUGHT_POKEMONS_FAIL = "GET_CAUGHT_POKEMONS";

export const ARE_ALL_CAUGHT_POKEMONS_LOADED = "ARE_ALL_CAUGHT_POKEMONS_LOADED";

export const CATCH_POKEMON_START = "CATCH_POKEMON_START";
export const CATCH_POKEMON_SUCCESS = "CATCH_POKEMON_SUCCESS";
export const CATCH_POKEMON_FAIL = "CATCH_POKEMON_FAIL";

export const GET_POKEMON_INFO_LOADING = "GET_POKEMON_INFO_LOADING";
export const GET_POKEMON_INFO_SUCCESS = "GET_POKEMON_INFO_SUCCESS";
export const GET_POKEMON_INFO_FAIL = "GET_POKEMON_INFO_FAIL";
