const PokemonsActionTypes = {
  CATCH_POKEMON_ASYNC: 'CATCH_POKEMON_ASYNC',
  CATCH_POKEMON: 'CATCH_POKEMON',
  SET_POKEMON_FREE_ASYNC: 'SET_POKEMON_FREE_ASYNC',
  SET_POKEMON_FREE: 'SET_POKEMON_FREE',
  GET_POKEMON_DATA: 'GET_POKEMON_DATA',
  GET_POKEMON_DATA_ASYNC: 'GET_POKEMON_DATA_ASYNC',
  SET_CURRENT_POKEMON: 'SET_CURRENT_POKEMON'
};

export default PokemonsActionTypes;
